### ISSUE TITLE
Improve Windows Support

### ISSUE THREAD

**Issue by Lymdun** [modelcontextprotocol/inspector#76]
When trying to launch `npx -y @modelcontextprotocol/inspector` on Windows (Powershell or cmd), you end up with an error because the launch command isn't properly built ; `PORT= node C:\Users\Lymdun\AppData\Local\npm-cache\_npx\5a9d879542beca3a\node_modules\@modelcontextprotocol\inspector\client\bin\cli.js exited with code 1`.

Current workaround is to launch client & server separately, for example:

- `node C:\\Users\\Lymdun\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\server\\build\\index.js`
- `node C:\\Users\\Lymdun\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\client\\bin\\cli.js`

**Comment by ashwin-ant** [comment]
Fixed in https://github.com/modelcontextprotocol/inspector/pull/79, will go out in the next release
