### ISSUE TITLE
Can't run "List Resources" a second time

### ISSUE THREAD

**Issue by perfectbase** [modelcontextprotocol/inspector#77]
I'm just getting started on building a custom server, so forgive me if I'm misunderstanding something.

I'm using the default example server that is created when running `npx @modelcontextprotocol/create-server`.

It seems that you can list the Notes by running "List Resources" and you can create a Note from the Tools tab.
But it doesn't seem to be possible to list the new notes after creating one.

Reproduction:
- create a new server
- build
- run the inspector
- connect
- click the List Resources button
- create a new note from the Tools tab
- Try to list the resources again (not possible)

**Comment by ashwin-ant** [comment]
Fair callout! I think adding a Reset or Clear button to the top of the List Resources section could be useful here.
