### ISSUE TITLE
npx @modelcontextprotocol/inspector doesn't connect properly

### ISSUE THREAD

**Issue by martinbechard** [modelcontextprotocol/inspector#92]
**Describe the bug**
I followed the steps in the documentation to run the inspector using npx, I got a weird error where after spawning the stdio server, the proxy would crash with Error in /sse route: TypeError: Cannot read properties of undefined (reading 'on')

I cloned the repo and it worked right away

**To Reproduce**
start the inspector with npx. Try to connect
1. 

**Expected behavior**
With the cloned repo, I can see my resources, tools, sampling etc. 

**Additional context**
You need to update the published version because it's unusable and wastes people's time. The latest from the repo works like a charm.

**Comment by ashwin-ant** [comment]
@martinbechard sorry about that. We just released version 0.2.7, which has the latest fixes. Do you mind trying again with `npx` to see if the issue persists?

**Comment by martinbechard** [comment]
The problem is fixed, thanks!


Le ven. 29 nov. 2024, à 09 h 00, Ashwin Bhat ***@***.***> a
écrit :
